name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:

  k8s-integration:
    name: Integration tests
    runs-on: ubuntu-latest
    uses: ./.github/workflows/k8s_integrate.yaml

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - k8s-integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.0.0-rc
        id: channel
      - name: Upload bundle to edge
        uses: canonical/charming-actions/upload-bundle@1.0.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          resource-overrides: "pgbouncer-image:2"
          channel: "${{ steps.channel.outputs.name }}"

