name: integration tests

on:
  workflow_call:
  pull_request:
  schedule:
    - cron:  '0 12 * * 3'

jobs:
  integration-test-k8s:
    runs-on: ubuntu-latest
    name: Integration tests for k8s charm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until https://bugs.launchpad.net/juju/+bug/1977582 is fixed.
          bootstrap-options: "--agent-version 2.9.29"
      - name: Run k8s integration tests
        run: tox -e k8s-integration
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          app: pgbouncer-k8s
