# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Update bundle

on: workflow_dispatch

jobs:
  update-bundle:
    name: Update bundle
    uses: canonical/data-platform-workflows/.github/workflows/update_bundle.yaml@lucas%2Fadd-arch-check
    with:
      path-to-bundle-file: releases/latest/postgresql-bundle.yaml
      reviewers: canonical/data-platform-postgresql
    secrets:
      token: ${{ secrets.PAT }}
